services:
    star-rating.twig.extension:
        class: CCC\StarRatingBundle\Extension\StarRatingTwigExtension
        tags:
            -  { name: twig.extension }

    star-rating.form.type:
        class: CCC\StarRatingBundle\Form\StarRatingType
        tags:
            - { name: form.type, alias: star_rating }
